#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# git-repo-for-each-branch-do "https://github.com/semiosis/prompts/" "$MYGIT/semiosis/prompt-tests/run-tests"| v

test -d "prompts" || exit 1

cd prompts

for fp in *; do
    if ! { test -f "$fp" && pl "$fp" | grep -q -P '\.prompt$'; }; then
        continue
    fi

    echo "$fp" | udl | hls purple
    delim="¬"
    IFS="$delim" read -r -d$'\1' version title < <(
        cat "$fp" | yq -r '[."prompt-version",.title] | join("'$delim'")')

    : "${version:="0"}"

    slug="$(printf -- "%s\n" "$title" | tr '\n' ' ' | sed 's/ $//' | slugify)"
    testfp="$MYGIT/semiosis/prompt-tests/results/${slug}-v${version}.txt"
    test -f "$testfp" && continue

    eval "set -- $(cat "$fp" | yq ".examples // empty | .[]" | s join ' ')"
    openai-complete "$fp" "$@" > "$testfp"
done

cd $MYGIT/semiosis/prompt-tests/
git add -A .
git commit -m "$(k f8)"
vc p